/**
 * Icon wrapper — maps Feather icon names to Lucide icons
 * API compatible with @expo/vector-icons/Feather
 * Uses lucide-react-native for consistent, modern icon system
 *
 * Feather → Lucide name mapping:
 * Most names are identical. Exceptions mapped below.
 * Avatar/user → user, plus-circle → circle-plus, file-text → file-text, etc.
 */

import React from 'react';
import { View, StyleSheet } from 'react-native';
import * as LucideIcons from 'lucide-react-native';

// Feather-to-Lucide name mapping for icons that differ
const NAME_MAP: Record<string, string> = {
  'plus-circle': 'CirclePlus',
  'log-in': 'LogIn',
  'log-out': 'LogOut',
  'user-plus': 'UserPlus',
  'arrow-left': 'ArrowLeft',
  'alert-circle': 'AlertCircle',
  'check-circle': 'CheckCircle',
  'chevron-down': 'ChevronDown',
  'chevron-up': 'ChevronUp',
  'chevron-right': 'ChevronRight',
  'trash-2': 'Trash2',
  'bar-chart-3': 'BarChart3',
  'loader-circle': 'LoaderCircle',
  'image-plus': 'ImagePlus',
  'wand-sparkles': 'WandSparkles',
  'camera': 'Camera',
  'settings': 'Settings',
  'file-text': 'FileText',
  'file-edit': 'FileEdit',
  'eye-off': 'EyeOff',
  'clock': 'Clock',
  'clock-arrow-up': 'ArrowUpNarrowWide',
  'sparkles': 'Sparkles',
  'circle-plus': 'CirclePlus',
  'rocket': 'Rocket',
  'lightbulb': 'Lightbulb',
  'user': 'User',
  'check': 'Check',
  'send': 'Send',
  'save': 'Save',
  'search': 'Search',
  'filter': 'Filter',
  'info': 'Info',
  'x': 'X',
  'zap': 'Zap',
  'play': 'Play',
  'music': 'Music',
  'video': 'Video',
  'image': 'Image',
  'link': 'Link',
  'crown': 'Crown',
  'bell': 'Bell',
  'eye': 'Eye',
  'circle': 'Circle',
  'store': 'Store',
  'shopping-bag': 'ShoppingBag',
  'briefcase': 'Briefcase',
  'globe': 'Globe',
  'instagram': 'Instagram',
  'twitter': 'Twitter',
  'facebook': 'Facebook',
  'youtube': 'Youtube',
  'tiktok': 'Music2',
  'menu': 'Menu',
  'more-horizontal': 'MoreHorizontal',
  'more-vertical': 'MoreVertical',
  'refresh-cw': 'RefreshCw',
  'refresh-ccw': 'RefreshCcw',
  'copy': 'Copy',
  'external-link': 'ExternalLink',
  'map-pin': 'MapPin',
  'phone': 'Phone',
  'mail': 'Mail',
  'message-circle': 'MessageCircle',
  'message-square': 'MessageSquare',
  'thumbs-up': 'ThumbsUp',
  'heart': 'Heart',
  'star': 'Star',
  'bookmark': 'Bookmark',
  'share-2': 'Share2',
  'download': 'Download',
  'upload': 'Upload',
  'calendar': 'Calendar',
  'clock': 'Clock',
  'activity': 'Activity',
  'airplay': 'Airplay',
  'anchor': 'Anchor',
  'aperture': 'Aperture',
  'archive': 'Archive',
  'at-sign': 'AtSign',
  'award': 'Award',
  'battery': 'Battery',
  'battery-charging': 'BatteryCharging',
  'bell-off': 'BellOff',
  'bluetooth': 'Bluetooth',
  'bold': 'Bold',
  'book': 'Book',
  'book-open': 'BookOpen',
  'box': 'Box',
  'briefcase': 'Briefcase',
  'brush': 'Brush',
  'bug': 'Bug',
  'compass': 'Compass',
  'credit-card': 'CreditCard',
  'crosshair': 'Crosshair',
  'database': 'Database',
  'delete': 'Delete',
  'dollar-sign': 'DollarSign',
  'droplet': 'Droplet',
  'edit': 'Edit',
  'edit-3': 'Edit3',
  'flag': 'Flag',
  'folder': 'Folder',
  'gift': 'Gift',
  'git-branch': 'GitBranch',
  'git-commit': 'GitCommit',
  'git-merge': 'GitMerge',
  'git-pull-request': 'GitPullRequest',
  'grid': 'Grid',
  'hard-drive': 'HardDrive',
  'hash': 'Hash',
  'headphones': 'Headphones',
  'help-circle': 'HelpCircle',
  'home': 'Home',
  'image': 'Image',
  'inbox': 'Inbox',
  'italic': 'Italic',
  'key': 'Key',
  'layers': 'Layers',
  'layout': 'Layout',
  'life-buoy': 'LifeBuoy',
  'link-2': 'Link2',
  'list': 'List',
  'loader': 'Loader',
  'lock': 'Lock',
  'map': 'Map',
  'maximize': 'Maximize',
  'maximize-2': 'Maximize2',
  'minimize': 'Minimize',
  'minimize-2': 'Minimize2',
  'minus': 'Minus',
  'monitor': 'Monitor',
  'moon': 'Moon',
  'move': 'Move',
  'navigation': 'Navigation',
  'navigation-2': 'Navigation2',
  'package': 'Package',
  'paperclip': 'Paperclip',
  'pause': 'Pause',
  'pause-circle': 'PauseCircle',
  'pen-tool': 'PenTool',
  'percent': 'Percent',
  'phone-call': 'PhoneCall',
  'phone-forwarded': 'PhoneForwarded',
  'phone-incoming': 'PhoneIncoming',
  'phone-missed': 'PhoneMissed',
  'phone-off': 'PhoneOff',
  'phone-outgoing': 'PhoneOutgoing',
  'pie-chart': 'PieChart',
  'plus': 'Plus',
  'plus-square': 'PlusSquare',
  'pocket': 'Pocket',
  'power': 'Power',
  'printer': 'Printer',
  'radio': 'Radio',
  'refresh-cw': 'RefreshCw',
  'repeat': 'Repeat',
  'rewind': 'Rewind',
  'rotate-ccw': 'RotateCcw',
  'rotate-cw': 'RotateCw',
  'rss': 'Rss',
  'scissors': 'Scissors',
  'server': 'Server',
  'shield': 'Shield',
  'shield-off': 'ShieldOff',
  'shopping-cart': 'ShoppingCart',
  'shuffle': 'Shuffle',
  'sidebar': 'Sidebar',
  'skip-back': 'SkipBack',
  'skip-forward': 'SkipForward',
  'slack': 'Slack',
  'sliders': 'Sliders',
  'smartphone': 'Smartphone',
  'smile': 'Smile',
  'speaker': 'Speaker',
  'square': 'Square',
  'stop-circle': 'StopCircle',
  'sun': 'Sun',
  'sunrise': 'Sunrise',
  'sunset': 'Sunset',
  'tablet': 'Tablet',
  'tag': 'Tag',
  'target': 'Target',
  'terminal': 'Terminal',
  'thermometer': 'Thermometer',
  'toggle-left': 'ToggleLeft',
  'toggle-right': 'ToggleRight',
  'tool': 'Tool',
  'trash': 'Trash',
  'trending-down': 'TrendingDown',
  'trending-up': 'TrendingUp',
  'triangle': 'Triangle',
  'truck': 'Truck',
  'tv': 'Tv',
  'twitter': 'Twitter',
  'type': 'Type',
  'umbrella': 'Umbrella',
  'underline': 'Underline',
  'unlock': 'Unlock',
  'user-check': 'UserCheck',
  'user-minus': 'UserMinus',
  'user-x': 'UserX',
  'users': 'Users',
  'video-off': 'VideoOff',
  'voicemail': 'Voicemail',
  'volume': 'Volume',
  'volume-1': 'Volume1',
  'volume-2': 'Volume2',
  'volume-x': 'VolumeX',
  'watch': 'Watch',
  'wifi': 'Wifi',
  'wind': 'Wind',
  'wrench': 'Wrench',
  'zoom-in': 'ZoomIn',
  'zoom-out': 'ZoomOut',
  // Custom business icons
  'google-business': 'Store',
  'instagram': 'Instagram',
};

interface IconProps {
  name: string;
  size?: number;
  color?: string;
  strokeWidth?: number;
}

export function Icon({ name, size = 24, color = '#0F172A', strokeWidth = 2 }: IconProps) {
  const lucideName = NAME_MAP[name] || pascalCase(name);

  // @ts-expect-error — dynamic lookup
  const LucideIcon = LucideIcons[lucideName];

  if (!LucideIcon) {
    // Fallback: render a placeholder
    return <View style={{ width: size, height: size }} />;
  }

  return <LucideIcon size={size} color={color} strokeWidth={strokeWidth} />;
}

function pascalCase(str: string): string {
  return str
    .split('-')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

export default Icon;
